version: 2.1

jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: cimg/python:3.10.1  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run Build
          command: pipenv run python evenodd.py 
  test:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: cimg/python:3.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run Test
          command: pipenv run python testevenodd.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build